# Generated by Django 4.1.3 on 2022-12-03 15:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import medcenter.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UserID', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='UserFirst_Name', max_length=32, validators=[medcenter.validators.validate_users], verbose_name='First name')),
                ('last_name', models.CharField(db_column='UserLast_Name', max_length=32, validators=[medcenter.validators.validate_users], verbose_name='Last name')),
                ('UserMobile_Phone', models.CharField(blank=True, default='', max_length=32, validators=[medcenter.validators.validate_phone], verbose_name='Mobile phone')),
                ('email', models.EmailField(blank=True, db_column='UserEmail', default='', max_length=128, validators=[medcenter.validators.validate_email])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.BigAutoField(primary_key=True, serialize=False)),
                ('EmpFirst_Name', models.CharField(max_length=30)),
                ('EmpLast_Name', models.CharField(max_length=30)),
                ('EmpMobile_Phone', models.CharField(max_length=30)),
                ('EmpEmail', models.CharField(max_length=100)),
                ('EmpPicture', models.ImageField(default='default.jpg', upload_to='emp_photos')),
                ('Salary', models.FloatField()),
                ('ManagerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medcenter.employee')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('Account_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Account_Type', models.CharField(max_length=6)),
                ('Balance', models.FloatField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('TransactionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Transaction_amount', models.FloatField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.useraccount')),
                ('empid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medcenter.employee')),
            ],
        ),
        migrations.CreateModel(
            name='UserAppointment',
            fields=[
                ('AppID', models.BigAutoField(primary_key=True, serialize=False)),
                ('AppCity', models.CharField(max_length=20)),
                ('AppClinicName', models.CharField(max_length=20)),
                ('AppMedCategory', models.CharField(max_length=40)),
                ('AppDoctor_Full_Name', models.CharField(max_length=30)),
                ('empid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medcenter.employee')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
