# Generated by Django 4.1.3 on 2022-12-03 18:07

from django.db import migrations, models
import medcenter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('medcenter', '0002_alter_customuser_usermobile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='UserMobile_Phone',
            field=models.CharField(blank=True, error_messages={'unique': 'This phone number already exists'}, help_text='Not required. Standart format is -> +XXX (XX) XXX-XXX-XXXX', max_length=32, unique=True, validators=[medcenter.validators.validate_phone], verbose_name='Mobile phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, db_column='UserEmail', error_messages={'unique': 'This email already exists'}, max_length=128, unique=True, validators=[medcenter.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(db_column='UserFirst_Name', help_text='This fields is required. Should be more than or equal to 5         and less than or equal to 25 characters. Accepts only lower and upper letters and digits.', max_length=32, validators=[medcenter.validators.validate_users], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(db_column='UserLast_Name', help_text='This fields is required. Should be more than or equal to 5         and less than or equal to 25 characters. Accepts only lower and upper letters and digits.', max_length=32, validators=[medcenter.validators.validate_users], verbose_name='Last name'),
        ),
    ]
