# Generated by Django 4.1.3 on 2022-12-06 16:47

from django.db import migrations, models
import medcenter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('medcenter', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_column='UserEmail', max_length=254, unique=True, validators=[medcenter.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(db_column='UserFirst_Name', help_text='This fields is required. Should be more than or equal to 2         and less than or equal to 25 characters. Accepts only lower and upper letters and digits.', max_length=32, validators=[medcenter.validators.validate_users], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(db_column='UserLast_Name', help_text='This fields is required. Should be more than or equal to 2         and less than or equal to 25 characters. Accepts only lower and upper letters and digits.', max_length=32, validators=[medcenter.validators.validate_users], verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='Transaction_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
