# Generated by Django 4.1.3 on 2022-12-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcenter', '0007_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
